# -*- coding: utf-8 -*-
"""Custom_ResNet50.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vLtImsMKvsW_hbgmdUKVyyTYWi6d9duT

## Step 1 — Upload Kaggle API Credentials
"""

from google.colab import files
files.upload()

"""## Step 2 — Configure Kaggle and Download Dataset"""

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/kaggle.json
!chmod 600 ~/.kaggle/kaggle.json
!kaggle competitions download -c state-farm-distracted-driver-detection -p /content/distracted_driver_data
!unzip -q /content/distracted_driver_data/state-farm-distracted-driver-detection.zip -d /content/distracted_driver_data/state-farm-distracted-driver-detection

"""## Step 3 — All Imports"""

# Commented out IPython magic to ensure Python compatibility.
import os
import cv2
import math
import h5py
import random
import pickle
import warnings
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from PIL import Image
from imutils import paths

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Model, load_model
from tensorflow.keras.layers import (
    Input, Add, Dense, Activation, ZeroPadding2D,
    BatchNormalization, Flatten, Conv2D, AveragePooling2D,
    MaxPooling2D, GlobalMaxPooling2D, Dropout
)
from tensorflow.keras.preprocessing.image import img_to_array, ImageDataGenerator
from tensorflow.keras.applications.imagenet_utils import preprocess_input
from tensorflow.keras.initializers import glorot_uniform
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau

from sklearn.preprocessing import LabelBinarizer
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

import tensorflow.keras.backend as K
K.set_image_data_format('channels_last')

warnings.filterwarnings('ignore')
# %matplotlib inline

print('TensorFlow version:', tf.__version__)
print('GPU available:', len(tf.config.list_physical_devices('GPU')) > 0)

"""## Step 4 — Verify Dataset Classes and Image Counts"""

BASE_PATH = '/content/distracted_driver_data/state-farm-distracted-driver-detection'
TRAIN_PATH = os.path.join(BASE_PATH, 'imgs', 'train')
DRIVER_CSV  = os.path.join(BASE_PATH, 'driver_imgs_list.csv')
WEIGHTS_PATH = os.path.join(BASE_PATH, 'resnet50_improved.weights.h5')
HISTORY_PATH = os.path.join(BASE_PATH, 'resnet50_history.pkl')

IMG_SIZE    = 128
BATCH_SIZE  = 32
EPOCHS      = 30
NUM_CLASSES = 10
LEARNING_RATE = 1e-4

CLASS_NAMES = [
    'safe driving',
    'texting - right',
    'talking on the phone - right',
    'texting - left',
    'talking on the phone - left',
    'operating the radio',
    'drinking',
    'reaching behind',
    'hair and makeup',
    'talking to passenger'
]

CLASS_CODES = {
    'c0': 0, 'c1': 1, 'c2': 2, 'c3': 3, 'c4': 4,
    'c5': 5, 'c6': 6, 'c7': 7, 'c8': 8, 'c9': 9
}

classes = sorted([c for c in os.listdir(TRAIN_PATH) if os.path.isdir(os.path.join(TRAIN_PATH, c))])
print('Classes found:', classes)
print('Number of classes:', len(classes))
for cls in classes:
    count = len(os.listdir(os.path.join(TRAIN_PATH, cls)))
    print(f'  {cls}: {count} images')

"""## Step 5 — Display Random Sample Images"""

all_image_paths = list(paths.list_images(TRAIN_PATH))

CLASS_LABELS = {
    'c0': 'safe driving',         'c1': 'texting - right',
    'c2': 'phone - right',        'c3': 'texting - left',
    'c4': 'phone - left',         'c5': 'operating radio',
    'c6': 'drinking',             'c7': 'reaching behind',
    'c8': 'hair and makeup',      'c9': 'talking to passenger'
}

random.shuffle(all_image_paths)
sample = all_image_paths[:25]

plt.figure(figsize=(14, 14))
plt.suptitle('Random Sample — Driver Distraction Classes', fontsize=14)
for i, path in enumerate(sample):
    plt.subplot(5, 5, i + 1)
    img = Image.open(path)
    plt.imshow(img)
    label = CLASS_LABELS.get(os.path.basename(os.path.dirname(path)), '')
    plt.title(label, fontsize=8)
    plt.axis('off')
plt.tight_layout(rect=[0, 0.02, 1, 0.96])
plt.show()

"""## Step 6 — Subject-Aware Train / Validation Split"""

# Load the driver/image mapping CSV
driver_df = pd.read_csv(DRIVER_CSV)
print('Driver CSV shape:', driver_df.shape)
print(driver_df.head())

# Unique subject IDs
all_subjects = driver_df['subject'].unique()
print(f'\nTotal unique drivers: {len(all_subjects)}')

# Reserve ~20% of drivers for validation
random.seed(42)
val_subjects = set(random.sample(list(all_subjects), k=max(1, int(len(all_subjects) * 0.20))))
train_subjects = set(all_subjects) - val_subjects

print(f'Train drivers : {len(train_subjects)}')
print(f'Val   drivers : {len(val_subjects)}')

# Build path lists — all images used (FIX: no 500-image cap)
train_paths, val_paths = [], []

for _, row in driver_df.iterrows():
    img_path = os.path.join(TRAIN_PATH, row['classname'], row['img'])
    if not os.path.exists(img_path):
        continue
    if row['subject'] in train_subjects:
        train_paths.append(img_path)
    else:
        val_paths.append(img_path)

print(f'\nTotal train images : {len(train_paths)}')
print(f'Total val   images : {len(val_paths)}')

"""## Step 7 — Preprocessor Classes"""

class SimplePreprocessor:
    """Resize image to a fixed width x height."""
    def __init__(self, width, height, inter=cv2.INTER_AREA):
        self.width  = width
        self.height = height
        self.inter  = inter

    def preprocess(self, image):
        return cv2.resize(image, (self.width, self.height), interpolation=self.inter)


class ImageToArrayPreprocessor:
    """Convert a PIL/cv2 image to a Keras-compatible numpy array."""
    def __init__(self, data_format=None):
        self.data_format = data_format

    def preprocess(self, image):
        return img_to_array(image, data_format=self.data_format)


class SimpleDatasetLoader:
    """Load images from a list of paths, apply preprocessors, return (data, labels)."""
    def __init__(self, preprocessors=None):
        self.preprocessors = preprocessors if preprocessors is not None else []

    def load(self, image_paths, verbose=500):
        data, labels = [], []
        for i, img_path in enumerate(image_paths):
            image = cv2.imread(img_path)

            if image is None:
                print("Skipped unreadable image:", img_path)
                continue
            image = cv2.imread(img_path)
            label = img_path.split(os.path.sep)[-2]
            for p in self.preprocessors:
                image = p.preprocess(image)
            data.append(image)
            labels.append(label)
            if verbose > 0 and (i + 1) % verbose == 0:
                print(f'[INFO] processed {i+1}/{len(image_paths)}')
        return np.array(data), np.array(labels)

import os
import tensorflow as tf
from sklearn.preprocessing import LabelBinarizer

# -------------------------------------------------
# Settings
# -------------------------------------------------
IMG_SIZE = 128
BATCH_SIZE = 8

# -------------------------------------------------
# Extract labels from folder names
# Example path:
# .../imgs/train/c3/img_123.jpg
# Label extracted:
# c3
# -------------------------------------------------
train_labels = [
    os.path.basename(os.path.dirname(path))
    for path in train_paths
]

val_labels = [
    os.path.basename(os.path.dirname(path))
    for path in val_paths
]

print("Training images   :", len(train_paths))
print("Validation images :", len(val_paths))

print("Training labels   :", len(train_labels))
print("Validation labels :", len(val_labels))

# -------------------------------------------------
# Convert labels into one-hot encoded arrays
# Use one shared LabelBinarizer for train and validation
# -------------------------------------------------
lb = LabelBinarizer()

y_train = lb.fit_transform(train_labels)
y_val = lb.transform(val_labels)

print("\nClass order:", lb.classes_)
print("y_train shape:", y_train.shape)
print("y_val shape  :", y_val.shape)

# -------------------------------------------------
# Function to load and preprocess one image
# Images are loaded only when needed
# -------------------------------------------------
def load_and_preprocess_image(image_path, label):
    image = tf.io.read_file(image_path)

    image = tf.image.decode_jpeg(
        image,
        channels=3
    )

    image = tf.image.resize(
        image,
        [IMG_SIZE, IMG_SIZE]
    )

    # Normalize pixel values from 0–255 to 0–1
    image = tf.cast(image, tf.float32) / 255.0

    return image, label

# -------------------------------------------------
# Create training dataset
# -------------------------------------------------
train_dataset = tf.data.Dataset.from_tensor_slices(
    (train_paths, y_train)
)

train_dataset = train_dataset.shuffle(
    buffer_size=len(train_paths),
    seed=42,
    reshuffle_each_iteration=True
)

train_dataset = train_dataset.map(
    load_and_preprocess_image,
    num_parallel_calls=tf.data.AUTOTUNE
)

train_dataset = train_dataset.batch(
    BATCH_SIZE
)

train_dataset = train_dataset.prefetch(
    tf.data.AUTOTUNE
)

# -------------------------------------------------
# Create validation dataset
# -------------------------------------------------
val_dataset = tf.data.Dataset.from_tensor_slices(
    (val_paths, y_val)
)

val_dataset = val_dataset.map(
    load_and_preprocess_image,
    num_parallel_calls=tf.data.AUTOTUNE
)

val_dataset = val_dataset.batch(
    BATCH_SIZE
)

val_dataset = val_dataset.prefetch(
    tf.data.AUTOTUNE
)

print("\nTraining dataset created successfully.")
print("Validation dataset created successfully.")

for images, labels in train_dataset.take(1):
    print("Image batch shape :", images.shape)
    print("Label batch shape :", labels.shape)
    print("Pixel range       :", images.numpy().min(), "to", images.numpy().max())

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

train_df = pd.DataFrame({
    "Class": train_labels,
    "Dataset": "Training"
})

val_df = pd.DataFrame({
    "Class": val_labels,
    "Dataset": "Validation"
})

plot_df = pd.concat(
    [train_df, val_df],
    ignore_index=True
)

plt.figure(figsize=(13, 5))

sns.countplot(
    data=plot_df,
    x="Class",
    hue="Dataset"
)

plt.title("Class Distribution — Training vs Validation")
plt.xlabel("Class Code")
plt.ylabel("Image Count")
plt.tight_layout()
plt.show()

import tensorflow as tf
import matplotlib.pyplot as plt

data_augmentation = tf.keras.Sequential([
    tf.keras.layers.RandomRotation(0.03),
    tf.keras.layers.RandomTranslation(
        height_factor=0.05,
        width_factor=0.05
    ),
    tf.keras.layers.RandomZoom(0.10),
    tf.keras.layers.RandomContrast(0.10)
], name="data_augmentation")

# Take one image batch from the tf.data pipeline
for image_batch, label_batch in train_dataset.take(1):
    sample_img = image_batch[0]

# Display augmented versions of one training image
plt.figure(figsize=(14, 4))
plt.suptitle("Augmented Versions of One Training Image", fontsize=12)

for i in range(8):
    augmented_img = data_augmentation(
        tf.expand_dims(sample_img, axis=0),
        training=True
    )

    plt.subplot(1, 8, i + 1)
    plt.imshow(tf.clip_by_value(augmented_img[0], 0, 1))
    plt.axis("off")

plt.tight_layout()
plt.show()

print("Augmentation pipeline ready.")

from tensorflow.keras.layers import (
    Conv2D,
    BatchNormalization,
    Activation,
    Add
)
from tensorflow.keras.initializers import glorot_uniform


def identity_block(X, f, filters, stage, block):
    """
    Identity block:
    The input and output dimensions remain the same.
    The shortcut path is added directly without resizing.
    """

    conv_name = "res" + str(stage) + block + "_"
    bn_name = "bn" + str(stage) + block + "_"

    f1, f2, f3 = filters
    bn_axis = 3

    # Save the original input for the skip connection
    X_skip = X

    # Main path: Component 1
    X = Conv2D(
        filters=f1,
        kernel_size=(1, 1),
        strides=(1, 1),
        padding="valid",
        name=conv_name + "1",
        kernel_initializer=glorot_uniform(seed=0)
    )(X)

    X = BatchNormalization(
        axis=bn_axis,
        name=bn_name + "1"
    )(X)

    X = Activation("relu")(X)

    # Main path: Component 2
    X = Conv2D(
        filters=f2,
        kernel_size=(f, f),
        strides=(1, 1),
        padding="same",
        name=conv_name + "2",
        kernel_initializer=glorot_uniform(seed=0)
    )(X)

    X = BatchNormalization(
        axis=bn_axis,
        name=bn_name + "2"
    )(X)

    X = Activation("relu")(X)

    # Main path: Component 3
    X = Conv2D(
        filters=f3,
        kernel_size=(1, 1),
        strides=(1, 1),
        padding="valid",
        name=conv_name + "3",
        kernel_initializer=glorot_uniform(seed=0)
    )(X)

    X = BatchNormalization(
        axis=bn_axis,
        name=bn_name + "3"
    )(X)

    # Add main path and shortcut path
    X = Add()([X, X_skip])

    X = Activation("relu")(X)

    return X


def convolutional_block(X, f, filters, stage, block, s=2):
    """
    Convolutional block:
    The input and output dimensions are different.
    A 1×1 convolution is applied to the shortcut path
    so that its dimensions match the main path.
    """

    conv_name = "res" + str(stage) + block + "_"
    bn_name = "bn" + str(stage) + block + "_"

    f1, f2, f3 = filters
    bn_axis = 3

    # Save the original input for the skip connection
    X_skip = X

    # Main path: Component 1
    X = Conv2D(
        filters=f1,
        kernel_size=(1, 1),
        strides=(s, s),
        padding="valid",
        name=conv_name + "1",
        kernel_initializer=glorot_uniform(seed=0)
    )(X)

    X = BatchNormalization(
        axis=bn_axis,
        name=bn_name + "1"
    )(X)

    X = Activation("relu")(X)

    # Main path: Component 2
    X = Conv2D(
        filters=f2,
        kernel_size=(f, f),
        strides=(1, 1),
        padding="same",
        name=conv_name + "2",
        kernel_initializer=glorot_uniform(seed=0)
    )(X)

    X = BatchNormalization(
        axis=bn_axis,
        name=bn_name + "2"
    )(X)

    X = Activation("relu")(X)

    # Main path: Component 3
    X = Conv2D(
        filters=f3,
        kernel_size=(1, 1),
        strides=(1, 1),
        padding="valid",
        name=conv_name + "3",
        kernel_initializer=glorot_uniform(seed=0)
    )(X)

    X = BatchNormalization(
        axis=bn_axis,
        name=bn_name + "3"
    )(X)

    # Shortcut path: resize dimensions using 1×1 convolution
    X_skip = Conv2D(
        filters=f3,
        kernel_size=(1, 1),
        strides=(s, s),
        padding="valid",
        name=conv_name + "skip",
        kernel_initializer=glorot_uniform(seed=0)
    )(X_skip)

    X_skip = BatchNormalization(
        axis=bn_axis,
        name=bn_name + "skip"
    )(X_skip)

    # Add main path and shortcut path
    X = Add()([X, X_skip])

    X = Activation("relu")(X)

    return X

from tensorflow.keras.layers import (
    Input,
    ZeroPadding2D,
    Conv2D,
    BatchNormalization,
    Activation,
    MaxPooling2D,
    GlobalAveragePooling2D,
    Dense,
    Dropout
)

from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.initializers import glorot_uniform


def build_resnet50(input_shape, num_classes):
    """
    Build an improved ResNet50-style model for
    driver distraction classification.
    """

    # Input image
    X_input = Input(
        shape=input_shape,
        name="input_image"
    )

    # Apply augmentation only during training
    X = data_augmentation(X_input)

    # ---------------------------------------------
    # Stage 1: Initial convolution and max pooling
    # ---------------------------------------------
    X = ZeroPadding2D(
        padding=(3, 3)
    )(X)

    X = Conv2D(
        filters=64,
        kernel_size=(7, 7),
        strides=(2, 2),
        name="conv1",
        kernel_initializer=glorot_uniform(seed=0)
    )(X)

    X = BatchNormalization(
        axis=3,
        name="bn1"
    )(X)

    X = Activation("relu")(X)

    X = MaxPooling2D(
        pool_size=(3, 3),
        strides=(2, 2)
    )(X)

    # ---------------------------------------------
    # Stage 2
    # ---------------------------------------------
    X = convolutional_block(
        X,
        f=3,
        filters=[64, 64, 256],
        stage=2,
        block="a",
        s=1
    )

    X = identity_block(
        X,
        3,
        [64, 64, 256],
        stage=2,
        block="b"
    )

    X = identity_block(
        X,
        3,
        [64, 64, 256],
        stage=2,
        block="c"
    )

    # ---------------------------------------------
    # Stage 3
    # ---------------------------------------------
    X = convolutional_block(
        X,
        f=3,
        filters=[128, 128, 512],
        stage=3,
        block="a",
        s=2
    )

    X = identity_block(X, 3, [128, 128, 512], stage=3, block="b")
    X = identity_block(X, 3, [128, 128, 512], stage=3, block="c")
    X = identity_block(X, 3, [128, 128, 512], stage=3, block="d")

    # ---------------------------------------------
    # Stage 4
    # ---------------------------------------------
    X = convolutional_block(
        X,
        f=3,
        filters=[256, 256, 1024],
        stage=4,
        block="a",
        s=2
    )

    X = identity_block(X, 3, [256, 256, 1024], stage=4, block="b")
    X = identity_block(X, 3, [256, 256, 1024], stage=4, block="c")
    X = identity_block(X, 3, [256, 256, 1024], stage=4, block="d")
    X = identity_block(X, 3, [256, 256, 1024], stage=4, block="e")
    X = identity_block(X, 3, [256, 256, 1024], stage=4, block="f")

    # ---------------------------------------------
    # Stage 5
    # ---------------------------------------------
    X = convolutional_block(
        X,
        f=3,
        filters=[512, 512, 2048],
        stage=5,
        block="a",
        s=2
    )

    X = identity_block(X, 3, [512, 512, 2048], stage=5, block="b")
    X = identity_block(X, 3, [512, 512, 2048], stage=5, block="c")

    # ---------------------------------------------
    # Classification head
    # ---------------------------------------------
    X = GlobalAveragePooling2D(
        name="global_average_pooling"
    )(X)

    X = Dense(
        units=512,
        activation="relu",
        kernel_initializer=glorot_uniform(seed=0),
        name="dense_512"
    )(X)

    X = Dropout(
        rate=0.5,
        name="dropout"
    )(X)

    X = Dense(
        units=num_classes,
        activation="softmax",
        name="output",
        kernel_initializer=glorot_uniform(seed=0)
    )(X)

    model = Model(
        inputs=X_input,
        outputs=X,
        name="ResNet50_Improved"
    )

    return model

NUM_CLASSES = 10
LEARNING_RATE = 0.0001

model = build_resnet50(
    input_shape=(IMG_SIZE, IMG_SIZE, 3),
    num_classes=NUM_CLASSES
)

model.compile(
    optimizer=Adam(
        learning_rate=LEARNING_RATE
    ),
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

from tensorflow.keras.callbacks import (
    ModelCheckpoint,
    EarlyStopping,
    ReduceLROnPlateau
)

import pickle

# -------------------------------------------------
# Training callbacks
# -------------------------------------------------
callbacks = [
    # Save the best model weights based on validation accuracy
    ModelCheckpoint(
        filepath=WEIGHTS_PATH,
        monitor="val_accuracy",
        save_best_only=True,
        save_weights_only=True,
        mode="max",
        verbose=1
    ),

    # Stop training if validation loss does not improve
    EarlyStopping(
        monitor="val_loss",
        patience=5,
        restore_best_weights=True,
        verbose=1
    ),

    # Reduce learning rate if validation loss stops improving
    ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=3,
        min_lr=1e-7,
        verbose=1
    )
]

# -------------------------------------------------
# Train model using memory-efficient batch datasets
# -------------------------------------------------
history = model.fit(
    train_dataset,
    epochs=EPOCHS,
    validation_data=val_dataset,
    callbacks=callbacks
)

# -------------------------------------------------
# Save training history
# -------------------------------------------------
with open(HISTORY_PATH, "wb") as file:
    pickle.dump(history.history, file)

print("Training complete.")
print("Best weights saved to:", WEIGHTS_PATH)
print("Training history saved to:", HISTORY_PATH)

with open(HISTORY_PATH, 'rb') as f:
    hist = pickle.load(f)

epochs_range = np.arange(1, len(hist['loss']) + 1)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Loss
axes[0].plot(epochs_range, hist['loss'],     label='Train loss')
axes[0].plot(epochs_range, hist['val_loss'], label='Val loss')
axes[0].set_title('Loss')
axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Loss')          # FIX: was missing / wrong in original
axes[0].legend()

# Accuracy  (FIX: y-axis label was 'Loss' in original)
axes[1].plot(epochs_range, hist['accuracy'],     label='Train accuracy')
axes[1].plot(epochs_range, hist['val_accuracy'], label='Val accuracy')
axes[1].set_title('Accuracy')
axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('Accuracy')      # FIX: was labelled 'Loss' in the original
axes[1].legend()

plt.suptitle('Training history', fontsize=13)
plt.tight_layout()
plt.show()

import numpy as np
from sklearn.metrics import accuracy_score, classification_report

# Load the weights saved at the best validation-accuracy epoch
model.load_weights(WEIGHTS_PATH)

print("Best weights loaded.")

# Predict using the memory-efficient validation dataset
predictions = model.predict(
    val_dataset,
    verbose=1
)

pred_indices = predictions.argmax(axis=1)

# Collect the actual one-hot encoded labels from val_dataset
true_labels = np.concatenate([
    labels.numpy()
    for _, labels in val_dataset
], axis=0)

true_indices = true_labels.argmax(axis=1)

# Calculate validation accuracy
validation_accuracy = accuracy_score(
    true_indices,
    pred_indices
)

print(
    f"\nDriver-wise validation accuracy: "
    f"{validation_accuracy:.4f}"
)

print("\nClassification Report:")

print(
    classification_report(
        true_indices,
        pred_indices,
        target_names=CLASS_NAMES,
        digits=4
    )
)

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(true_indices, pred_indices)

plt.figure(figsize=(12, 10))

sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=CLASS_NAMES,
    yticklabels=CLASS_NAMES
)

plt.title("Driver-Wise Validation Confusion Matrix")
plt.xlabel("Predicted Class")
plt.ylabel("Actual Class")
plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

import os
import cv2
import random
import numpy as np
import matplotlib.pyplot as plt


def predict_single_image(image_path, show=True):
    """
    Load one image, run inference, and optionally display the result.

    Returns:
        predicted_class_name
        confidence_percent
    """

    # Load image using OpenCV
    image_bgr = cv2.imread(image_path)

    if image_bgr is None:
        raise FileNotFoundError(
            f"Could not load image: {image_path}"
        )

    # Convert BGR to RGB to match the training pipeline
    image_rgb = cv2.cvtColor(
        image_bgr,
        cv2.COLOR_BGR2RGB
    )

    # Resize and normalize exactly as done during training
    resized = cv2.resize(
        image_rgb,
        (IMG_SIZE, IMG_SIZE)
    )

    processed = resized.astype("float32") / 255.0

    # Add batch dimension:
    # (128, 128, 3) → (1, 128, 128, 3)
    processed = np.expand_dims(
        processed,
        axis=0
    )

    # Predict class probabilities
    preds = model.predict(
        processed,
        verbose=0
    )

    pred_idx = int(
        np.argmax(preds[0])
    )

    confidence = float(
        preds[0][pred_idx]
    ) * 100

    pred_name = CLASS_NAMES[pred_idx]

    if show:
        # Extract actual class folder from validation-image path
        actual_code = os.path.basename(
            os.path.dirname(image_path)
        )

        actual_idx = CLASS_CODES.get(
            actual_code,
            -1
        )

        actual_name = (
            CLASS_NAMES[actual_idx]
            if actual_idx >= 0
            else "Unknown"
        )

        # Green title for correct result, red for incorrect result
        colour = (
            "green"
            if pred_idx == actual_idx
            else "red"
        )

        plt.figure(figsize=(5, 5))

        plt.imshow(image_rgb)

        plt.title(
            f"Actual: {actual_name}\n"
            f"Predicted: {pred_name} "
            f"({confidence:.1f}%)",
            color=colour,
            fontsize=11
        )

        plt.axis("off")
        plt.show()

    return pred_name, confidence


# Test on one random validation image
sample_path = random.choice(val_paths)

print("Selected image:", sample_path)

predict_single_image(sample_path)

