# -*- coding: utf-8 -*-
"""InceptionV3_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YXIOnCZM0CpwanXfkjbrnNR4rtKA1hKH
"""

!pip install -q kaggle

import os
import zipfile
import random
import time
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2
from google.colab import files
import tensorflow as tf
from tensorflow.keras import layers, Model, regularizers
from tensorflow.keras.applications import InceptionV3
from tensorflow.keras.applications.inception_v3 import preprocess_input
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau
from sklearn.preprocessing import LabelBinarizer
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)
print("TensorFlow version:", tf.__version__)

uploaded = files.upload()
kaggle_file_name = list(uploaded.keys())[0]
os.makedirs("/root/.kaggle", exist_ok=True)
!cp "{kaggle_file_name}" /root/.kaggle/kaggle.json
!chmod 600 /root/.kaggle/kaggle.json
print("Kaggle API file uploaded successfully.")

BASE_DIR = "/content/statefarm"
os.makedirs(BASE_DIR, exist_ok=True)
!kaggle competitions download -c state-farm-distracted-driver-detection -p "{BASE_DIR}"
print("Dataset downloaded.")

def extract_all_zips(root_dir):
    extracted_any = True
    while extracted_any:
        extracted_any = False
        for root, dirs, files_list in os.walk(root_dir):
            for file_name in files_list:
                if file_name.endswith(".zip"):
                    zip_path = os.path.join(root, file_name)
                    extract_folder = os.path.join(
                        root,
                        file_name.replace(".zip", "")
                    )
                    if not os.path.exists(extract_folder):
                        os.makedirs(extract_folder, exist_ok=True)
                        print("Extracting:", zip_path)
                        with zipfile.ZipFile(zip_path, "r") as zip_ref:
                            zip_ref.extractall(extract_folder)
                        extracted_any = True
extract_all_zips(BASE_DIR)
print("All zip files extracted.")

def find_file(root_dir, target_file):
    for root, dirs, files_list in os.walk(root_dir):
        if target_file in files_list:
            return os.path.join(root, target_file)
    return None
def find_train_dir(root_dir):
    for root, dirs, files_list in os.walk(root_dir):
        if os.path.basename(root) == "train":
            class_folders = [
                d for d in os.listdir(root)
                if os.path.isdir(os.path.join(root, d)) and d.startswith("c")
            ]
            if len(class_folders) == 10:
                return root
    return None
DRIVER_CSV = find_file(BASE_DIR, "driver_imgs_list.csv")
TRAIN_DIR = find_train_dir(BASE_DIR)
print("Driver CSV:", DRIVER_CSV)
print("Train directory:", TRAIN_DIR)
if DRIVER_CSV is None:
    raise FileNotFoundError("driver_imgs_list.csv not found.")
if TRAIN_DIR is None:
    raise FileNotFoundError("Train folder with c0-c9 class folders not found.")

driver_df = pd.read_csv(DRIVER_CSV)
print(driver_df.head())
print()
print("Total images:", len(driver_df))
print("Total drivers:", driver_df["subject"].nunique())
print("Classes:", sorted(driver_df["classname"].unique()))

CLASS_DESCRIPTION = {
    "c0": "Safe driving",
    "c1": "Texting - right hand",
    "c2": "Talking on phone - right hand",
    "c3": "Texting - left hand",
    "c4": "Talking on phone - left hand",
    "c5": "Operating radio",
    "c6": "Drinking",
    "c7": "Reaching behind",
    "c8": "Hair and makeup",
    "c9": "Talking to passenger"
}
for class_code, description in CLASS_DESCRIPTION.items():
    print(class_code, ":", description)

def create_image_path(row):
    return os.path.join(
        TRAIN_DIR,
        row["classname"],
        row["img"]
    )
driver_df["image_path"] = driver_df.apply(
    create_image_path,
    axis=1
)
driver_df["exists"] = driver_df["image_path"].apply(os.path.exists)
print(driver_df["exists"].value_counts())
if not driver_df["exists"].all():
    missing_df = driver_df[driver_df["exists"] == False]
    print(missing_df.head())
    raise FileNotFoundError("Some image paths are missing.")
print("All image paths are valid.")

class_counts = driver_df["classname"].value_counts().sort_index()
print(class_counts)
plt.figure(figsize=(8, 5))
plt.bar(class_counts.index, class_counts.values)
plt.xlabel("Class")
plt.ylabel("Number of Images")
plt.title("Overall Dataset Class Distribution")
plt.show()

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)
all_subjects = sorted(driver_df["subject"].unique())
print("All subjects:", all_subjects)
print("Number of subjects:", len(all_subjects))
random.shuffle(all_subjects)
val_ratio = 0.20
num_val_subjects = max(1, int(len(all_subjects) * val_ratio))
val_subjects = set(all_subjects[:num_val_subjects])
train_subjects = set(all_subjects[num_val_subjects:])
train_df = driver_df[driver_df["subject"].isin(train_subjects)].copy()
val_df = driver_df[driver_df["subject"].isin(val_subjects)].copy()
print("Training subjects:", sorted(train_subjects))
print("Validation subjects:", sorted(val_subjects))
print("Number of training subjects:", len(train_subjects))
print("Number of validation subjects:", len(val_subjects))
print("Training images:", len(train_df))
print("Validation images:", len(val_df))

overlap = set(train_df["subject"]).intersection(set(val_df["subject"]))
print("Driver overlap:", overlap)
if len(overlap) != 0:
    raise ValueError("Driver leakage detected.")
else:
    print("No driver leakage. Driver-wise split is correct.")

train_counts = train_df["classname"].value_counts().sort_index()
val_counts = val_df["classname"].value_counts().sort_index()
print("Training class distribution:")
print(train_counts)
print("\nValidation class distribution:")
print(val_counts)
plt.figure(figsize=(8, 5))
plt.bar(train_counts.index, train_counts.values)
plt.xlabel("Class")
plt.ylabel("Number of Images")
plt.title("Training Class Distribution")
plt.show()
plt.figure(figsize=(8, 5))
plt.bar(val_counts.index, val_counts.values)
plt.xlabel("Class")
plt.ylabel("Number of Images")
plt.title("Validation Class Distribution")
plt.show()

train_paths = train_df["image_path"].values
val_paths = val_df["image_path"].values
train_labels = train_df["classname"].values
val_labels = val_df["classname"].values
label_binarizer = LabelBinarizer()
y_train = label_binarizer.fit_transform(train_labels).astype("float32")
y_val = label_binarizer.transform(val_labels).astype("float32")
CLASS_NAMES = list(label_binarizer.classes_)
print("Class order:", CLASS_NAMES)
print("y_train shape:", y_train.shape)
print("y_val shape:", y_val.shape)

IMG_SIZE = 299
BATCH_SIZE = 8
NUM_CLASSES = 10
def load_image_for_inception(image_path, label):
    image = tf.io.read_file(image_path)
    image = tf.image.decode_jpeg(
        image,
        channels=3
    )
    image = tf.image.resize(
        image,
        [IMG_SIZE, IMG_SIZE]
    )
    image = tf.cast(
        image,
        tf.float32
    )
    return image, label
train_dataset = tf.data.Dataset.from_tensor_slices(
    (train_paths, y_train)
)
train_dataset = train_dataset.shuffle(
    buffer_size=len(train_paths),
    seed=SEED,
    reshuffle_each_iteration=True
)
train_dataset = train_dataset.map(
    load_image_for_inception,
    num_parallel_calls=tf.data.AUTOTUNE
)
train_dataset = train_dataset.batch(BATCH_SIZE)
train_dataset = train_dataset.prefetch(
    tf.data.AUTOTUNE
)
val_dataset = tf.data.Dataset.from_tensor_slices(
    (val_paths, y_val)
)
val_dataset = val_dataset.map(
    load_image_for_inception,
    num_parallel_calls=tf.data.AUTOTUNE
)
val_dataset = val_dataset.batch(BATCH_SIZE)
val_dataset = val_dataset.prefetch(
    tf.data.AUTOTUNE
)
print("Datasets created successfully.")

def show_sample_images(dataframe, num_images=12):
    sample_df = dataframe.sample(
        n=num_images,
        random_state=SEED
    )
    plt.figure(figsize=(12, 8))
    for i, (_, row) in enumerate(sample_df.iterrows()):
        image = tf.io.read_file(row["image_path"])
        image = tf.image.decode_jpeg(image, channels=3)
        plt.subplot(3, 4, i + 1)
        plt.imshow(image.numpy().astype("uint8"))
        plt.title(
            f"{row['classname']}\n"
            f"{CLASS_DESCRIPTION[row['classname']]}"
        )
        plt.axis("off")
    plt.tight_layout()
    plt.show()
show_sample_images(train_df, num_images=12)

data_augmentation = tf.keras.Sequential(
    [
        layers.RandomRotation(0.05),
        layers.RandomTranslation(
            height_factor=0.08,
            width_factor=0.08
        ),
        layers.RandomZoom(0.15),
        layers.RandomContrast(0.15),
        layers.RandomBrightness(0.15)
    ],
    name="data_augmentation"
)
print("Stronger data augmentation created.")
## Step 18 — Loss Function with Label Smoothing
loss_function = tf.keras.losses.CategoricalCrossentropy(
    label_smoothing=0.05
)
print("Loss function with label smoothing created.")

tf.keras.backend.clear_session()
def build_inceptionv3_model(
    input_shape=(299, 299, 3),
    num_classes=10
):
    inputs = layers.Input(
        shape=input_shape,
        name="input_image"
    )
    x = data_augmentation(inputs)
    x = layers.Lambda(
        preprocess_input,
        name="inception_preprocessing"
    )(x)
    base_model = InceptionV3(
        include_top=False,
        weights="imagenet",
        input_tensor=x
    )
    base_model.trainable = False
    x = base_model.output
    x = layers.GlobalAveragePooling2D(
        name="global_average_pooling"
    )(x)
    x = layers.Dense(
        256,
        activation="relu",
        kernel_regularizer=regularizers.l2(1e-4),
        name="dense_256_l2"
    )(x)
    x = layers.Dropout(
        0.5,
        name="dropout_0_5"
    )(x)
    x = layers.Dense(
        128,
        activation="relu",
        kernel_regularizer=regularizers.l2(1e-4),
        name="dense_128_l2"
    )(x)
    x = layers.Dropout(
        0.3,
        name="dropout_0_3"
    )(x)
    outputs = layers.Dense(
        num_classes,
        activation="softmax",
        name="output"
    )(x)
    model = Model(
        inputs=inputs,
        outputs=outputs,
        name="InceptionV3_DriverDistraction"
    )
    return model, base_model
model, base_model = build_inceptionv3_model(
    input_shape=(IMG_SIZE, IMG_SIZE, 3),
    num_classes=NUM_CLASSES
)

model.compile(
    optimizer=Adam(learning_rate=1e-4),
    loss=loss_function,
    metrics=["accuracy"]
)
model.summary()

STAGE1_WEIGHTS_PATH = os.path.join(
    BASE_DIR,
    "inceptionv3_stage1_best.weights.h5"
)
callbacks_stage1 = [
    ModelCheckpoint(
        filepath=STAGE1_WEIGHTS_PATH,
        monitor="val_accuracy",
        save_best_only=True,
        save_weights_only=True,
        mode="max",
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=3,
        min_lr=1e-6,
        verbose=1
    )
]
history_stage1 = model.fit(
    train_dataset,
    epochs=15,
    validation_data=val_dataset,
    callbacks=callbacks_stage1
)

def plot_training_history(history, title_prefix):
    acc = history.history["accuracy"]
    val_acc = history.history["val_accuracy"]
    loss = history.history["loss"]
    val_loss = history.history["val_loss"]
    epochs_range = range(1, len(acc) + 1)
    plt.figure(figsize=(8, 5))
    plt.plot(epochs_range, acc, label="Training Accuracy")
    plt.plot(epochs_range, val_acc, label="Validation Accuracy")
    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.title(f"{title_prefix} Accuracy")
    plt.legend()
    plt.show()
    plt.figure(figsize=(8, 5))
    plt.plot(epochs_range, loss, label="Training Loss")
    plt.plot(epochs_range, val_loss, label="Validation Loss")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.title(f"{title_prefix} Loss")
    plt.legend()
    plt.show()
plot_training_history(
    history_stage1,
    "Stage 1 - Frozen InceptionV3"
)

model.load_weights(STAGE1_WEIGHTS_PATH)
print("Best Stage 1 weights loaded.")
## Step 24 — Stage 2 Fine-Tuning Setup (from mixed7)
base_model.trainable = True
fine_tune_at = None
for i, layer in enumerate(base_model.layers):
    if layer.name == "mixed7":
        fine_tune_at = i
        break
if fine_tune_at is None:
    raise ValueError("Layer 'mixed7' not found in InceptionV3.")
for layer in base_model.layers[:fine_tune_at]:
    layer.trainable = False
for layer in base_model.layers[fine_tune_at:]:
    layer.trainable = True
for layer in base_model.layers:
    if isinstance(layer, tf.keras.layers.BatchNormalization):
        layer.trainable = False
model.compile(
    optimizer=Adam(learning_rate=1e-5),
    loss=loss_function,
    metrics=["accuracy"]
)
print("Total InceptionV3 layers:", len(base_model.layers))
print("Fine-tuning starts from layer:", fine_tune_at, f"({base_model.layers[fine_tune_at].name})")
trainable_params = np.sum([
    np.prod(v.shape)
    for v in model.trainable_weights
])
non_trainable_params = np.sum([
    np.prod(v.shape)
    for v in model.non_trainable_weights
])
print("Trainable parameters:", trainable_params)
print("Non-trainable parameters:", non_trainable_params)

from google.colab import drive
drive.mount("/content/drive")

import os
import shutil
import pickle

DRIVE_MODEL_DIR = (
    "/content/drive/MyDrive/"
    "DriverDistraction/InceptionV3"
)

os.makedirs(DRIVE_MODEL_DIR, exist_ok=True)

DRIVE_STAGE1_PATH = os.path.join(
    DRIVE_MODEL_DIR,
    "inceptionv3_stage1_best.weights.h5"
)

# Check whether Stage 1 checkpoint exists
if not os.path.exists(STAGE1_WEIGHTS_PATH):
    raise FileNotFoundError(
        f"Stage 1 weights not found: {STAGE1_WEIGHTS_PATH}"
    )

# Copy best Stage 1 weights to Google Drive
shutil.copy2(
    STAGE1_WEIGHTS_PATH,
    DRIVE_STAGE1_PATH
)

print("Stage 1 weights saved safely to:")
print(DRIVE_STAGE1_PATH)

# Optional: save Stage 1 training history
STAGE1_HISTORY_PATH = os.path.join(
    DRIVE_MODEL_DIR,
    "inceptionv3_stage1_history.pkl"
)

with open(STAGE1_HISTORY_PATH, "wb") as file:
    pickle.dump(history_stage1.history, file)

print("Stage 1 history saved to:")
print(STAGE1_HISTORY_PATH)

from google.colab import drive
drive.mount("/content/drive")

import os

DRIVE_STAGE1_PATH = (
    "/content/drive/MyDrive/"
    "DriverDistraction/InceptionV3/"
    "inceptionv3_stage1_best.weights.h5"
)

model.load_weights(DRIVE_STAGE1_PATH)

print("Stage 1 best weights loaded successfully.")

base_model.trainable = True
fine_tune_at = None
for i, layer in enumerate(base_model.layers):
    if layer.name == "mixed7":
        fine_tune_at = i
        break
if fine_tune_at is None:
    raise ValueError("Layer 'mixed7' not found in InceptionV3.")
for layer in base_model.layers[:fine_tune_at]:
    layer.trainable = False
for layer in base_model.layers[fine_tune_at:]:
    layer.trainable = True
for layer in base_model.layers:
    if isinstance(layer, tf.keras.layers.BatchNormalization):
        layer.trainable = False
model.compile(
    optimizer=Adam(learning_rate=1e-5),
    loss=loss_function,
    metrics=["accuracy"]
)
print("Total InceptionV3 layers:", len(base_model.layers))
print("Fine-tuning starts from layer:", fine_tune_at, f"({base_model.layers[fine_tune_at].name})")
trainable_params = np.sum([
    np.prod(v.shape)
    for v in model.trainable_weights
])
non_trainable_params = np.sum([
    np.prod(v.shape)
    for v in model.non_trainable_weights
])
print("Trainable parameters:", trainable_params)
print("Non-trainable parameters:", non_trainable_params)

FINE_TUNED_WEIGHTS_PATH = os.path.join(
    BASE_DIR,
    "inceptionv3_finetuned_best.weights.h5"
)

callbacks_stage2 = [
    ModelCheckpoint(
        filepath=FINE_TUNED_WEIGHTS_PATH,
        monitor="val_accuracy",
        save_best_only=True,
        save_weights_only=True,
        mode="max",
        verbose=1
    ),
    EarlyStopping(
        monitor="val_accuracy",
        patience=4,
        restore_best_weights=True,
        mode="max",
        verbose=1
    ),
    ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=2,
        min_lr=1e-7,
        verbose=1
    )
]
history_stage2 = model.fit(
    train_dataset,
    epochs=20,
    validation_data=val_dataset,
    callbacks=callbacks_stage2
)

import matplotlib.pyplot as plt


def plot_training_history(history, title_prefix):
    accuracy = history.history["accuracy"]
    validation_accuracy = history.history["val_accuracy"]

    loss = history.history["loss"]
    validation_loss = history.history["val_loss"]

    epochs_range = range(1, len(accuracy) + 1)

    # Accuracy graph
    plt.figure(figsize=(8, 5))

    plt.plot(
        epochs_range,
        accuracy,
        label="Training Accuracy"
    )

    plt.plot(
        epochs_range,
        validation_accuracy,
        label="Validation Accuracy"
    )

    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")
    plt.title(f"{title_prefix} Accuracy")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()

    # Loss graph
    plt.figure(figsize=(8, 5))

    plt.plot(
        epochs_range,
        loss,
        label="Training Loss"
    )

    plt.plot(
        epochs_range,
        validation_loss,
        label="Validation Loss"
    )

    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.title(f"{title_prefix} Loss")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()


print("plot_training_history function created.")

plot_training_history(
    history_stage2,
    "Stage 2 - Fine-Tuned InceptionV3"
)

import os
import pickle

STAGE2_HISTORY_PATH = os.path.join(
    BASE_DIR,
    "inceptionv3_stage2_history.pkl"
)

with open(STAGE2_HISTORY_PATH, "wb") as file:
    pickle.dump(
        history_stage2.history,
        file
    )

print("Stage 2 history saved to:")
print(STAGE2_HISTORY_PATH)

from google.colab import drive
drive.mount("/content/drive")

import os
import shutil

DRIVE_MODEL_DIR = (
    "/content/drive/MyDrive/"
    "DriverDistraction/InceptionV3"
)

os.makedirs(DRIVE_MODEL_DIR, exist_ok=True)

SOURCE_HISTORY_PATH = (
    "/content/statefarm/"
    "inceptionv3_stage2_history.pkl"
)

DRIVE_HISTORY_PATH = os.path.join(
    DRIVE_MODEL_DIR,
    "inceptionv3_stage2_history.pkl"
)

if not os.path.exists(SOURCE_HISTORY_PATH):
    raise FileNotFoundError(
        f"History file not found: {SOURCE_HISTORY_PATH}"
    )

shutil.copy2(
    SOURCE_HISTORY_PATH,
    DRIVE_HISTORY_PATH
)

print("Stage 2 history copied safely to:")
print(DRIVE_HISTORY_PATH)

import os

FINE_TUNED_WEIGHTS_PATH = (
    "/content/drive/MyDrive/"
    "DriverDistraction/InceptionV3/"
    "inceptionv3_finetuned_best.weights.h5"
)

print(
    "Stage 2 weights exist:",
    os.path.exists(FINE_TUNED_WEIGHTS_PATH)
)

import os

for root, dirs, files in os.walk("/content"):
    for file in files:
        if file.endswith(".weights.h5"):
            print(os.path.join(root, file))

import os
import shutil

SOURCE_STAGE2_PATH = (
    "/content/statefarm/"
    "inceptionv3_finetuned_best.weights.h5"
)

DRIVE_STAGE2_PATH = (
    "/content/drive/MyDrive/"
    "DriverDistraction/InceptionV3/"
    "inceptionv3_finetuned_best.weights.h5"
)

os.makedirs(
    os.path.dirname(DRIVE_STAGE2_PATH),
    exist_ok=True
)

shutil.copy2(
    SOURCE_STAGE2_PATH,
    DRIVE_STAGE2_PATH
)

print("Stage 2 weights copied safely to:")
print(DRIVE_STAGE2_PATH)

print(
    "Stage 2 weights exist:",
    os.path.exists(DRIVE_STAGE2_PATH)
)

model.load_weights(DRIVE_STAGE2_PATH)

print("Best Stage 2 weights loaded successfully.")

FINAL_MODEL_PATH = (
    "/content/drive/MyDrive/"
    "DriverDistraction/InceptionV3/"
    "inceptionv3_driver_distraction.keras"
)

model.save(FINAL_MODEL_PATH)

print("Final full model saved to:")
print(FINAL_MODEL_PATH)

import os

BASE_PATH = (
    "/content/drive/MyDrive/"
    "DriverDistraction/InceptionV3"
)

required_files = [
    "inceptionv3_stage1_best.weights.h5",
    "inceptionv3_finetuned_best.weights.h5",
    "inceptionv3_stage1_history.pkl",
    "inceptionv3_stage2_history.pkl",
    "inceptionv3_driver_distraction.keras",
]

print("Checking files in:")
print(BASE_PATH)
print("-" * 60)

all_ok = True

for file_name in required_files:
    full_path = os.path.join(BASE_PATH, file_name)

    if os.path.exists(full_path):
        size_mb = os.path.getsize(full_path) / (1024 ** 2)

        print(
            f"FOUND  | {file_name} "
            f"| {size_mb:.2f} MB"
        )
    else:
        print(f"MISSING | {file_name}")
        all_ok = False

print("-" * 60)

if all_ok:
    print("All InceptionV3 files are safely saved.")
    print("You can close Colab.")
else:
    print("Some files are missing. Do not close Colab yet.")

model.load_weights(FINE_TUNED_WEIGHTS_PATH)
predictions = model.predict(
    val_dataset,
    verbose=1
)
pred_indices = np.argmax(
    predictions,
    axis=1
)
true_labels = np.concatenate(
    [
        labels.numpy()
        for _, labels in val_dataset
    ],
    axis=0
)
true_indices = np.argmax(
    true_labels,
    axis=1
)

val_accuracy = accuracy_score(
    true_indices,
    pred_indices
)
print(f"Final driver-wise validation accuracy: {val_accuracy:.4f}")
print(
    classification_report(
        true_indices,
        pred_indices,
        target_names=CLASS_NAMES,
        digits=4
    )
)

cm = confusion_matrix(
    true_indices,
    pred_indices
)
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=CLASS_NAMES
)
fig, ax = plt.subplots(figsize=(10, 10))
disp.plot(
    ax=ax,
    xticks_rotation=45,
    values_format="d"
)
plt.title("Confusion Matrix - InceptionV3 Transfer Learning")
plt.show()

print("Per-class accuracy:")
for i, class_name in enumerate(CLASS_NAMES):
    class_mask = true_indices == i
    if np.sum(class_mask) > 0:
        class_acc = accuracy_score(
            true_indices[class_mask],
            pred_indices[class_mask]
        )
    else:
        class_acc = 0.0
    print(
        f"{class_name} - {CLASS_DESCRIPTION[class_name]}: "
        f"{class_acc:.4f}"
    )
## Step 31 — Inference Speed Measurement
def measure_inference_speed(model, dataset, num_batches=30):
    total_time = 0.0
    total_images = 0
    for images, labels in dataset.take(num_batches):
        start_time = time.time()
        _ = model.predict(
            images,
            verbose=0
        )
        end_time = time.time()
        total_time += end_time - start_time
        total_images += images.shape[0]
    avg_time_per_image = total_time / total_images
    fps = 1.0 / avg_time_per_image
    return avg_time_per_image, fps
avg_time, fps = measure_inference_speed(
    model,
    val_dataset,
    num_batches=30
)
print(f"Average inference time per image: {avg_time * 1000:.2f} ms")
print(f"Approximate FPS: {fps:.2f}")

def predict_single_image(image_path, show=True):
    image_bgr = cv2.imread(image_path)
    if image_bgr is None:
        raise FileNotFoundError(
            f"Could not read image: {image_path}"
        )
    image_rgb = cv2.cvtColor(
        image_bgr,
        cv2.COLOR_BGR2RGB
    )
    resized = cv2.resize(
        image_rgb,
        (IMG_SIZE, IMG_SIZE)
    )
    processed = np.expand_dims(
        resized.astype("float32"),
        axis=0
    )
    preds = model.predict(
        processed,
        verbose=0
    )
    pred_idx = int(np.argmax(preds[0]))
    confidence = float(preds[0][pred_idx]) * 100
    pred_class = CLASS_NAMES[pred_idx]
    pred_description = CLASS_DESCRIPTION[pred_class]
    actual_class = os.path.basename(
        os.path.dirname(image_path)
    )
    actual_description = CLASS_DESCRIPTION[actual_class]
    correct = pred_class == actual_class
    if show:
        plt.figure(figsize=(5, 5))
        plt.imshow(image_rgb)
        title_text = (
            f"Actual: {actual_class} - {actual_description}\n"
            f"Predicted: {pred_class} - {pred_description}\n"
            f"Confidence: {confidence:.2f}%"
        )
        plt.title(title_text)
        plt.axis("off")
        plt.show()
    return {
        "actual_class": actual_class,
        "actual_description": actual_description,
        "predicted_class": pred_class,
        "predicted_description": pred_description,
        "confidence": confidence,
        "correct": correct
    }
sample_image_path = random.choice(list(val_paths))
result = predict_single_image(
    sample_image_path,
    show=True
)
print(result)

def show_multiple_predictions(num_images=12):
    sample_paths = random.sample(
        list(val_paths),
        num_images
    )
    plt.figure(figsize=(12, 8))
    for i, image_path in enumerate(sample_paths):
        image_bgr = cv2.imread(image_path)
        if image_bgr is None:
            continue
        image_rgb = cv2.cvtColor(
            image_bgr,
            cv2.COLOR_BGR2RGB
        )
        resized = cv2.resize(
            image_rgb,
            (IMG_SIZE, IMG_SIZE)
        )
        processed = np.expand_dims(
            resized.astype("float32"),
            axis=0
        )
        preds = model.predict(
            processed,
            verbose=0
        )
        pred_idx = int(np.argmax(preds[0]))
        confidence = float(preds[0][pred_idx]) * 100
        pred_class = CLASS_NAMES[pred_idx]
        actual_class = os.path.basename(
            os.path.dirname(image_path)
        )
        plt.subplot(3, 4, i + 1)
        plt.imshow(image_rgb)
        plt.title(
            f"A: {actual_class}\n"
            f"P: {pred_class} ({confidence:.1f}%)"
        )
        plt.axis("off")
    plt.tight_layout()
    plt.show()
show_multiple_predictions(num_images=12)

SAVED_MODEL_PATH = os.path.join(
    BASE_DIR,
    "inceptionv3_driver_distraction.keras"
)
model.save(SAVED_MODEL_PATH)
print("Model saved to:")
print(SAVED_MODEL_PATH)

